// =============================================================================
// db-logic.unit.test.ts — Pure/data tests (no MongoDB required)
// =============================================================================

import { describe, it, expect } from "vitest";
import { COLLECTION_OPTIONS, INDEXES, isValidTransactionDate } from "./ingest-transaction-core.js";

// ---------------------------------------------------------------------------
// COLLECTION_OPTIONS
// ---------------------------------------------------------------------------

describe("COLLECTION_OPTIONS structure", () => {
  const schema = COLLECTION_OPTIONS.validator!.$jsonSchema as Record<string, unknown>;
  const properties = schema.properties as Record<string, Record<string, unknown>>;
  const required = schema.required as string[];

  it("has a $jsonSchema validator with bsonType object", () => {
    expect(schema).toBeDefined();
    expect(schema.bsonType).toBe("object");
  });

  it("validationLevel is strict", () => {
    expect(COLLECTION_OPTIONS.validationLevel).toBe("strict");
  });

  it("validationAction is error", () => {
    expect(COLLECTION_OPTIONS.validationAction).toBe("error");
  });

  it("additionalProperties is true (allows _id and future fields)", () => {
    expect(schema.additionalProperties).toBe(true);
  });

  it("required array contains all 15 expected field names", () => {
    const expectedFields = [
      "date",
      "merchant",
      "amount",
      "description",
      "category",
      "issuer",
      "card_last_four",
      "imported_at",
      "source_file",
      "eligibility_reason",
      "eligible_fsa",
      "eligible_dcfsa",
      "eligible_fsa_confidence",
      "eligible_dcfsa_confidence",
      "eligibility_scored_at",
    ];
    expect(required).toHaveLength(15);
    for (const field of expectedFields) {
      expect(required).toContain(field);
    }
  });

  it("required array does not contain _id (auto-generated by MongoDB)", () => {
    expect(required).not.toContain("_id");
  });

  it("date field enforces YYYY-MM-DD pattern", () => {
    expect(properties.date.pattern).toBe("^\\d{4}-\\d{2}-\\d{2}$");
    expect(properties.date.bsonType).toBe("string");
  });

  it("card_last_four field enforces 4-digit pattern", () => {
    expect(properties.card_last_four.pattern).toBe("^\\d{4}$");
    expect(properties.card_last_four.bsonType).toBe("string");
  });

  it("amount is bsonType double", () => {
    expect(properties.amount.bsonType).toBe("double");
  });

  it("eligible_fsa_confidence is bounded 0–1", () => {
    expect(properties.eligible_fsa_confidence.minimum).toBe(0);
    expect(properties.eligible_fsa_confidence.maximum).toBe(1);
  });

  it("eligible_dcfsa_confidence is bounded 0–1", () => {
    expect(properties.eligible_dcfsa_confidence.minimum).toBe(0);
    expect(properties.eligible_dcfsa_confidence.maximum).toBe(1);
  });

  it("all eligibility fields are nullable (bsonType arrays containing 'null')", () => {
    const nullableFields = [
      "eligibility_reason",
      "eligible_fsa",
      "eligible_dcfsa",
      "eligible_fsa_confidence",
      "eligible_dcfsa_confidence",
      "eligibility_scored_at",
    ];
    for (const field of nullableFields) {
      const bsonType = properties[field].bsonType as string[];
      expect(Array.isArray(bsonType), `${field}.bsonType should be an array`).toBe(true);
      expect(bsonType, `${field} should allow null`).toContain("null");
    }
  });

  it("imported_at is bsonType date (not nullable)", () => {
    expect(properties.imported_at.bsonType).toBe("date");
  });
});

// ---------------------------------------------------------------------------
// INDEXES
// ---------------------------------------------------------------------------

describe("INDEXES structure", () => {
  it("has exactly 6 index definitions", () => {
    expect(INDEXES).toHaveLength(6);
  });

  it("all index names are unique strings", () => {
    const names = INDEXES.map((i) => i.name);
    expect(new Set(names).size).toBe(names.length);
    for (const name of names) {
      expect(typeof name).toBe("string");
      expect(name.length).toBeGreaterThan(0);
    }
  });

  it("imported_at_desc has key { imported_at: -1 }", () => {
    const idx = INDEXES.find((i) => i.name === "imported_at_desc");
    expect(idx).toBeDefined();
    expect(idx!.key).toEqual({ imported_at: -1 });
  });

  it("card_last_four has key { card_last_four: 1 }", () => {
    const idx = INDEXES.find((i) => i.name === "card_last_four");
    expect(idx).toBeDefined();
    expect(idx!.key).toEqual({ card_last_four: 1 });
  });

  it("date_desc has key { date: -1 }", () => {
    const idx = INDEXES.find((i) => i.name === "date_desc");
    expect(idx).toBeDefined();
    expect(idx!.key).toEqual({ date: -1 });
  });

  it("eligible_fsa index has sparse: true", () => {
    const idx = INDEXES.find((i) => i.name === "eligible_fsa");
    expect(idx).toBeDefined();
    expect(idx!.sparse).toBe(true);
  });

  it("eligible_dcfsa index has sparse: true", () => {
    const idx = INDEXES.find((i) => i.name === "eligible_dcfsa");
    expect(idx).toBeDefined();
    expect(idx!.sparse).toBe(true);
  });

  it("imported_at_eligible_fsa is a composite index with two keys", () => {
    const idx = INDEXES.find((i) => i.name === "imported_at_eligible_fsa");
    expect(idx).toBeDefined();
    expect(Object.keys(idx!.key)).toHaveLength(2);
    expect(idx!.key).toMatchObject({ imported_at: -1, eligible_fsa: 1 });
  });

  it("no index has unique: true (deduplication is intentionally absent)", () => {
    for (const idx of INDEXES) {
      expect(idx.unique).toBeUndefined();
    }
  });

  it("every index key direction is 1 or -1", () => {
    for (const idx of INDEXES) {
      for (const [field, dir] of Object.entries(idx.key)) {
        expect(
          [1, -1],
          `index "${idx.name}" field "${field}" has invalid direction`,
        ).toContain(dir);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// isValidTransactionDate
// ---------------------------------------------------------------------------

describe("isValidTransactionDate", () => {
  it("accepts a well-formed date", () => {
    expect(isValidTransactionDate("2025-02-14")).toBe(true);
  });

  it("accepts edge dates with syntactically valid digits (regex only, not range)", () => {
    // Month 13 is invalid calendar-wise, but the regex is format-only.
    expect(isValidTransactionDate("2025-13-01")).toBe(true);
  });

  it("rejects a date with a 2-digit year", () => {
    expect(isValidTransactionDate("25-02-14")).toBe(false);
  });

  it("rejects slash-separated dates", () => {
    expect(isValidTransactionDate("2025/02/14")).toBe(false);
  });

  it("rejects an empty string", () => {
    expect(isValidTransactionDate("")).toBe(false);
  });

  it("rejects single-digit month or day", () => {
    expect(isValidTransactionDate("2025-2-4")).toBe(false);
  });

  it("rejects US-format dates (MM-DD-YYYY)", () => {
    expect(isValidTransactionDate("02-14-2025")).toBe(false);
  });
});
